"""
Multi-format export service.
Generates TXT, DOCX, and PDF files from summary data.
"""
import logging
from io import BytesIO
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

logger = logging.getLogger(__name__)


def export_as_txt(title: str, summary_text: str, topics: list = None) -> bytes:
    """Export summary as plain text."""
    lines = [
        f"Summary: {title}",
        "=" * 60,
        "",
        summary_text,
        "",
    ]
    if topics:
        lines.extend(["", "Topics: " + ", ".join(topics)])
    return "\n".join(lines).encode("utf-8")


def export_as_docx(title: str, summary_text: str, topics: list = None) -> bytes:
    """Export summary as a styled DOCX document."""
    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    sub = doc.add_paragraph("AI-Generated Summary")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.color.rgb = RGBColor(108, 92, 231)
    sub.runs[0].font.size = Pt(12)

    doc.add_paragraph("")  # spacer

    # Summary content
    for paragraph in summary_text.split("\n"):
        paragraph = paragraph.strip()
        if not paragraph:
            continue
        if paragraph.startswith("•") or paragraph.startswith("-"):
            p = doc.add_paragraph(paragraph[1:].strip(), style="List Bullet")
        else:
            p = doc.add_paragraph(paragraph)
            p.paragraph_format.space_after = Pt(6)

    # Topics section
    if topics:
        doc.add_paragraph("")
        doc.add_heading("Key Topics", level=2)
        topics_para = doc.add_paragraph(", ".join(topics))
        topics_para.runs[0].font.color.rgb = RGBColor(0, 210, 160)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph("Generated by BookSumAI")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].font.color.rgb = RGBColor(150, 150, 150)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_as_pdf(title: str, summary_text: str, topics: list = None) -> bytes:
    """Export summary as a styled PDF document."""
    from fpdf import FPDF

    class SummaryPDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(108, 92, 231)
            self.cell(0, 10, "BookSumAI", new_x="LMARGIN", new_y="NEXT", align="R")
            self.ln(2)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f"Page {self.page_no()}", align="C")

    pdf = SummaryPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 50)
    pdf.multi_cell(0, 12, title, align="C")
    pdf.ln(4)

    # Subtitle
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(108, 92, 231)
    pdf.cell(0, 8, "AI-Generated Summary", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    # Divider
    pdf.set_draw_color(108, 92, 231)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(8)

    # Summary body
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)

    for paragraph in summary_text.split("\n"):
        paragraph = paragraph.strip()
        if not paragraph:
            pdf.ln(4)
            continue
        if paragraph.startswith("•") or paragraph.startswith("-"):
            pdf.set_x(25)
            pdf.multi_cell(160, 7, f"  {paragraph}")
        else:
            pdf.multi_cell(0, 7, paragraph)
        pdf.ln(2)

    # Topics
    if topics:
        pdf.ln(6)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 30, 50)
        pdf.cell(0, 10, "Key Topics", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(0, 160, 120)
        pdf.multi_cell(0, 7, ", ".join(topics))

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
